Repository interlay/interbtc-ui, pull requests merged in 2022-08, with the labels that each got.

#457 Feature/usd amount formatting
  src/assets/locales/en/translation.json
  src/common/utils/utils.ts
  src/components/IssueUI/BTCPaymentPendingStatusUI/index.tsx
  src/components/IssueUI/WhoopsStatusUI/index.tsx
  src/components/IssueUI/index.tsx
  src/components/PriceInfo/index.tsx
  src/components/RedeemUI/RedeemRequestStatusUI/ReimbursedRedeemRequest/index.tsx
  src/components/RedeemUI/RedeemRequestStatusUI/RetriedRedeemRequest/index.tsx
  src/components/RedeemUI/ReimburseStatusUI/index.tsx
  src/components/RedeemUI/index.tsx
  src/pages/Bridge/BurnForm/index.tsx
  src/pages/Bridge/IssueForm/index.tsx
  src/pages/Bridge/RedeemForm/SubmittedRedeemRequestModal/index.tsx
  src/pages/Bridge/RedeemForm/index.tsx
  src/pages/Dashboard/sub-pages/Home/LockedCollateralsCard/index.tsx
  src/pages/Dashboard/sub-pages/Home/WrappedTokenCard/index.tsx
  src/pages/Dashboard/sub-pages/IssueRequests/UpperContent/index.tsx
  src/pages/Dashboard/sub-pages/Vaults/LockedCollateralCard/index.tsx
  src/pages/Staking/index.tsx
  src/pages/Transfer/CrossChainTransferForm/index.tsx
  src/pages/Vaults/Vault/RequestIssueModal/index.tsx
  src/pages/Vaults/Vault/UpdateCollateralModal/index.tsx
  src/utils/hooks/api/get-vault-overview.ts
Labels: enhancement

#417 Refactor/currency updates
  package.json
  src/App.tsx
  src/common/actions/general.actions.ts
  src/common/actions/vault.actions.ts
  src/common/reducers/general.reducer.ts
  src/common/reducers/vault.reducer.ts
  src/common/types/actions.types.ts
  src/common/types/util.types.ts
  src/common/types/vault.types.ts
  src/common/utils/utils.ts
  src/components/RedeemUI/RedeemRequestStatusUI/ReimbursedRedeemRequest/index.tsx
  src/components/Tokens/index.tsx
  src/components/Vaults/index.tsx
  src/config/relay-chains.tsx
  src/config/vaults.ts
  src/pages/Bridge/BurnForm/index.tsx
  src/pages/Bridge/IssueForm/index.tsx
  src/pages/Bridge/RedeemForm/index.tsx
  src/pages/Bridge/index.tsx
  src/pages/Dashboard/IssuedChart/index.tsx
  src/pages/Dashboard/cards/OracleStatusCard/index.tsx
  src/pages/Dashboard/sub-pages/Home/LockedCollateralsCard/index.tsx
  src/pages/Dashboard/sub-pages/Oracles/OraclesTable/index.tsx
  src/pages/Dashboard/sub-pages/RedeemRequests/UpperContent/RedeemedChart/index.tsx
  src/pages/Dashboard/sub-pages/RedeemRequests/UpperContent/index.tsx
  src/pages/Dashboard/sub-pages/Vaults/LockedCollateralCard/index.tsx
  src/pages/Dashboard/sub-pages/Vaults/VaultsTable/index.tsx
  src/pages/Dashboard/sub-pages/Vaults/index.tsx
  src/pages/Staking/index.tsx
  src/pages/Transfer/TransferForm/index.tsx
  src/pages/Vaults/Vault/ClaimRewardsButton/index.tsx
  src/pages/Vaults/Vault/ReplaceTable/index.tsx
  src/pages/Vaults/Vault/RequestIssueModal/index.tsx
  src/pages/Vaults/Vault/RequestRedeemModal/index.tsx
  src/pages/Vaults/Vault/RequestReplacementModal/index.tsx
  src/pages/Vaults/Vault/UpdateCollateralModal/index.tsx
  src/pages/Vaults/Vault/VaultIssueRequestsTable/index.tsx
  src/pages/Vaults/Vault/VaultRedeemRequestsTable/index.tsx
  src/pages/Vaults/Vault/VaultStatusStatPanel/index.tsx
  src/pages/Vaults/Vault/index.tsx
  src/parts/Topbar/index.tsx
  src/services/fetchers/cumulative-volumes-fetcher.ts
  src/services/fetchers/issues-fetcher.ts
  src/services/fetchers/oracle-exchange-rates-fetcher.ts
  src/services/fetchers/redeems-fetcher.ts
  src/services/hooks/use-cumulative-collateral-volumes.ts
  src/services/hooks/use-token-balance.ts
  src/types/currency.ts
  src/utils/constants/currency.ts
  src/utils/helpers/async-filter.ts
  src/utils/helpers/currencies.ts
  src/utils/helpers/vaults.ts
  src/utils/hooks/api/get-vault-overview.ts
  src/utils/hooks/api/use-get-available-vaults.tsx
  src/utils/hooks/api/use-get-collateral-thresholds.tsx
  src/utils/hooks/api/use-get-vaults.tsx
  src/utils/relay-chain-api/transfer-to-relay-chain.ts
  src/utils/relay-chain-api/types.ts
  yarn.lock
Labels: enhancement

#460 Version bump
  package.json
  src/pages/Bridge/IssueForm/index.tsx
  src/pages/Dashboard/sub-pages/RedeemRequests/RedeemRequestsTable/index.tsx
  src/utils/helpers/vaults.ts
  src/utils/relay-chain-api/transfer-to-parachain.ts
  src/utils/relay-chain-api/transfer-to-relay-chain.ts
Labels: bug

#459 Feature/locale formatting
  src/component-library/TokenBalance/TokenBalance.stories.tsx
  src/component-library/TokenBalance/TokenBalance.tsx
  src/component-library/TokenField/TokenField.stories.tsx
  src/component-library/TokenField/TokenField.tsx
  src/pages/NewVaultDashboard/components/CollateralModal/CollateralModal.tsx
  src/pages/NewVaultDashboard/components/IssueRedeemModal/IssueRedeemModal.tsx
  src/pages/Vaults/index.tsx
Labels: enhancement

#466 Feature/number formatting
  src/App.tsx
  src/assets/locales/en/translation.json
  src/common/utils/utils.ts
  src/component-library/NewVaultsTable/NewVaultsTable.stories.tsx
  src/component-library/NewVaultsTable/NewVaultsTable.tsx
  src/component-library/TokenField/TokenField.stories.tsx
  src/component-library/VaultCard/VaultCard.stories.tsx
  src/component-library/VaultCard/VaultCard.tsx
  src/components/IssueUI/IssueRequestStatusUI/CompletedIssueRequest/index.tsx
  src/components/IssueUI/IssueRequestStatusUI/ReceivedIssueRequest/index.tsx
  src/components/IssueUI/index.tsx
  src/components/RedeemUI/RedeemRequestStatusUI/CompletedRedeemRequest/index.tsx
  src/components/RedeemUI/RedeemRequestStatusUI/DefaultRedeemRequest/index.tsx
  src/components/RedeemUI/index.tsx
  src/components/Vaults/VaultsSelector/index.tsx
  src/pages/Dashboard/cards/ActiveVaultsCard/index.tsx
  src/pages/Dashboard/cards/BTCRelayCard/index.tsx
  src/pages/Dashboard/cards/CollateralizationCard/index.tsx
  src/pages/Dashboard/cards/OracleStatusCard/index.tsx
  src/pages/Dashboard/sub-pages/BTCRelay/BlocksTable/index.tsx
  src/pages/Dashboard/sub-pages/BTCRelay/BlockstreamCard/index.tsx
  src/pages/Dashboard/sub-pages/Home/ActiveCollatorsCard/index.tsx
  src/pages/Dashboard/sub-pages/IssueRequests/IssueRequestsTable/index.tsx
  src/pages/Dashboard/sub-pages/IssueRequests/UpperContent/index.tsx
  src/pages/Dashboard/sub-pages/Oracles/OraclesTable/index.tsx
  src/pages/Dashboard/sub-pages/RedeemRequests/RedeemRequestsTable/index.tsx
  src/pages/Dashboard/sub-pages/RedeemRequests/UpperContent/index.tsx
  src/pages/Dashboard/sub-pages/Vaults/VaultsTable/index.tsx
  src/pages/NewVaultDashboard/NewVaultDashboard.tsx
  src/pages/Staking/index.tsx
  src/pages/Transactions/IssueRequestsTable/index.tsx
  src/pages/Transactions/RedeemRequestsTable/index.tsx
  src/pages/Vaults/Vault/ReplaceTable/index.tsx
  src/pages/Vaults/Vault/UpdateCollateralModal/index.tsx
  src/pages/Vaults/Vault/VaultIssueRequestsTable/index.tsx
  src/pages/Vaults/Vault/VaultRedeemRequestsTable/index.tsx
  src/pages/Vaults/Vault/index.tsx
  src/pages/Vaults/index.tsx
  src/services/fetchers/cumulative-volumes-fetcher.ts
  src/services/fetchers/oracle-exchange-rates-fetcher.ts
  src/utils/helpers/vaults.ts
Labels: bug, enhancement
